// Componets
export { default as CardsWrapper } from "./Card/CardsWrapper.svelte"
export { default as Card } from "./Card/Card.svelte"
export { default as Button } from "./Button/Button.svelte"
export { default as Footer } from "./Footer/Footer.svelte"
export { default as Navbar } from "./Nav/Nav.svelte"
export { default as Carousel } from "./Carousel/Carousel.svelte"
export { default as MoviesAndTVShowsSection } from "./MoviesAndTVShowsSection/MoviesAndTVShows.svelte"
export { default as RecomandationSection } from "./RecomandationSection/RecomendationMovies.svelte"
export { default as PromoSection } from "./PromoSection/PromoSetion.svelte"
export { default as TopActorsSection } from "./TopActorsSection/TopActorSection.svelte"
