export { default as MoviesAndTVShowsSection } from "./MoviesAndTVShowsSection/MoviesAndTVShows.svelte"
export { default as Footer } from "./Footer/Footer.svelte"
export { default as RecomandationSection } from "./RecomandationSection/RecomendationMovies.svelte"
export { default as PromoSection } from "./PromoSection/PromoSetion.svelte"
export { default as TopActorsSection } from "./TopActorsSection/TopActorSection.svelte"
export { default as Navbar } from "./Navbar/Navbar.svelte"
